.TH MENAREANTS-SERVER 6 "February 25, 2007" Linux "Server Manual"
.SH NAME
menareants-server \- Men Are Ants' server
.SH SYNOPSIS
\fBmenareants-server [-hnsv] [-c \fIconfiguration_file\fB]\fR
.SH DESCRIPTIO
.PP
This server can receive clients to play a game.
.SH OPTIONS
.TP
\fB\-c\fR \fIconfiguration_file\fR
Use a specific configuration file.
.TP
\fB\-h\fR
Show help.
.TP
\fB\-n\fR
Don't launch in background.
.TP
\fB\-s\fR
No output.
.TP
\fB\-v\fR
Display Men Are Ants Daemon's version
.SH "SEE ALSO"
.BR menareants (6),
.BR menareants-meta-server (6).

.SH AUTHOR
.PP
MenAreAnts Daemon is written by Romain Bignon <romain@menareants.org>.
