.TH MENAREANTS 6 "February 25, 2007" Linux "Game Manual"
.SH NAME
menareants \- A fun strategic game
.SH SYNOPSIS
menareants
.SH DESCRIPTION
.PP
Connected to a server, you can play against an Artificial Intelligence, or
with and against your friends, from 2 to 8 players!
.PP
This is a turn by turn game. Firstly, this is the morning and each player have
to make all actions at the same time, and to press Ready button.
When every players are readies, this is
animation time, where you can see all events in the day, with engagements, etc.
.br
At the end of turn, this is a new day, and a new morning to prepare units.
.br
.SH CONTROLS
.PP
Global shortcuts:
.br
*
.B F1:
Show help screen
.br
*
.B F11:
Toggle full-screen
.br
*
.B <>^v:
Scroll map on screen
.br
*
.B Return:
Enter a message to send it to other players.
.br
          You can send message to everybody (
.B RETURN
), or only to yours allies (
.B CTRL+RETURN
).
.br
*
.B m:
You can display chat's history by maintain this key.
.br
*
.B n:
Change music
.br
*
.B C-A-p:
You are ready

.PP
Unit interactions:
.br
*
.B Tab:
Find idling units
.br
*
.B <>^v:
Move the unit
.br
*
.B SPACE:
If a boat, a train or a plane is selected, you can extract
the unit contained by pressing this key, and click on the
destination case (in blue).
.br

.SH "SEE ALSO"
.BR menareants-server (6),
.BR menareants-meta-server (6).


.SH AUTHOR
.PP
MenAreAnts is written by Romain Bignon <romain@menareants.org>.
.PP
Graphics are made by Thomas Tourette.
.PP
Contributors:
.br
- lodesi: patches
.br
- yeKcim: graphics
.br
- phh: patch
